#!/bin/sh

LTR=$1
LAN=$2

TARGET="./support/transform.ml"

# exit on error
set -e

# remove existing file to force recompilation
rm -f $TARGET
# compile the transformation
dune exec lnc/bin/compile_ltr.exe $LTR | ocamlformat --enable-outside-detected-project --profile=janestreet --margin=100 --name=$TARGET - > $TARGET
# link with the driver program and execute
dune exec support/transformer.exe $LAN
